import type { KbArticle } from './types';

export const KB_ARTICLES: KbArticle[] = [
  {
    slug: 'welcome-to-solartech',
    title: 'Welcome to SolarTech',
    summary: 'Overview of the platform and who it is built for.',
    categoryId: 'getting-started',
    tags: ['overview', 'onboarding'],
    readMinutes: 4,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'p', text: 'SolarTech is an AI-powered solar management platform for installers, solar companies, asset owners, and LGUs in the Philippines. You can monitor live production, generate quotations, manage maintenance, and bill clients from one place.' },
      { type: 'h2', text: 'Who uses SolarTech?' },
      { type: 'ul', items: [
        'Solar companies and EPCs — fleet monitoring, quotations, and client portals',
        'Installers — marketplace presence, work orders, and device onboarding',
        'Homeowners and clients — view production and invoices (read-only)',
        'LGU officers — province-level smart city analytics (Enterprise)',
      ]},
      { type: 'h2', text: 'Core modules' },
      { type: 'ul', items: [
        'Dashboard — KPIs across systems and devices',
        'Solar Systems — sites you install and monitor',
        'Quotations — physics-based sizing and ROI',
        'Devices & IoT — MQTT telemetry from inverters, meters, and gateways',
        'Maintenance — tickets and technician dispatch',
        'Billing — invoices and revenue tracking',
      ]},
      { type: 'callout', variant: 'tip', title: 'Quick start', text: 'Register an organization, add your first solar system, then register a device and publish sample telemetry using the edge gateway guide in infra/gateway.' },
    ],
  },
  {
    slug: 'create-your-first-system',
    title: 'Create your first solar system',
    summary: 'Add a site, set capacity and location, and link devices.',
    categoryId: 'getting-started',
    tags: ['systems', 'setup'],
    readMinutes: 5,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'p', text: 'A solar system represents one installation site — a home, commercial roof, or utility-scale array. All devices and telemetry roll up to a system.' },
      { type: 'h2', text: 'Steps' },
      { type: 'ol', items: [
        'Open Solar Systems from the sidebar.',
        'Click Add system (or use the empty-state button).',
        'Enter the client name, address, province, and installed capacity (kW).',
        'Choose grid type: on-grid, hybrid, or off-grid — this affects quotation battery defaults.',
        'Save. The system appears on your dashboard and in Smart City aggregates (if enabled).',
      ]},
      { type: 'h2', text: 'Best practices' },
      { type: 'ul', items: [
        'Use the real province for accurate peak sun hours in quotations.',
        'Set capacity close to nameplate DC/AC rating for meaningful KPI comparisons.',
        'Assign a client user later so they can log in and view production only.',
      ]},
      { type: 'callout', variant: 'info', text: 'You need the solar_company or installer role to create systems. Clients can view systems shared with their organization.' },
    ],
  },
  {
    slug: 'solar-quotations-guide',
    title: 'Solar quotations guide',
    summary: 'Run the sizing wizard, interpret ROI, and send proposals.',
    categoryId: 'quotations',
    tags: ['quotations', 'roi', 'sales'],
    readMinutes: 7,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'p', text: 'The quotation engine estimates system size from monthly kWh usage, roof area, utility rate, and province-specific peak sun hours. It builds an equipment list and payback period automatically.' },
      { type: 'h2', text: 'Creating a quotation' },
      { type: 'ol', items: [
        'Go to Quotations → New Quotation.',
        'Enter monthly consumption (kWh), average bill or utility rate (₱/kWh), and roof area (m²).',
        'Select province and grid type; enable battery if hybrid/off-grid.',
        'Review panel count, inverter size, and total installed cost.',
        'Save as draft, send to client, or mark approved when they accept.',
      ]},
      { type: 'h2', text: 'Understanding the numbers' },
      { type: 'ul', items: [
        'Performance ratio (~78%) accounts for inverter losses, temperature, and soiling.',
        'Payback years = total cost ÷ annual savings from avoided grid energy.',
        '25-year savings use a small annual degradation factor on production.',
        'CO₂ offset uses a Philippines grid factor for reporting.',
      ]},
      { type: 'callout', variant: 'tip', title: 'AI enhancements', text: 'When OpenAI is configured, you can request AI narrative recommendations on the quotation detail page. Review numbers before sharing with customers.' },
    ],
  },
  {
    slug: 'connect-iot-devices',
    title: 'Connect IoT devices via MQTT',
    summary: 'Register devices, copy MQTT topics, and publish telemetry.',
    categoryId: 'devices-iot',
    tags: ['mqtt', 'telemetry', 'gateway'],
    readMinutes: 8,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'p', text: 'Devices publish JSON telemetry to your MQTT broker. The API ingests messages and marks devices online when status heartbeats arrive.' },
      { type: 'h2', text: 'Registration' },
      { type: 'ol', items: [
        'Open Devices & IoT → Register device.',
        'Pick device type (ESP32, Raspberry Pi, inverter, smart meter, etc.).',
        'Link the device to a solar system.',
        'Open the device detail page and copy organization ID, system ID, client ID, and topics from Connect this device.',
      ]},
      { type: 'h2', text: 'Topic layout' },
      { type: 'code', text: 'solartech/{orgId}/{systemId}/{mqttClientId}/telemetry\nsolartech/{orgId}/{systemId}/{mqttClientId}/status' },
      { type: 'h2', text: 'Telemetry payload example' },
      { type: 'code', text: '{\n  "timestamp": "2026-05-28T12:00:00Z",\n  "metrics": {\n    "powerOutputW": 4200,\n    "voltageV": 230,\n    "energyTodayKwh": 18.4\n  }\n}' },
      { type: 'h2', text: 'Local testing' },
      { type: 'p', text: 'Use the reference gateway in infra/gateway: set ORG_ID, SYSTEM_ID, MQTT_CLIENT_ID, and broker credentials, then run npm run publish-loop.' },
      { type: 'callout', variant: 'warning', title: 'Production', text: 'Enable MQTT on the API (MQTT_ENABLED=true) and use TLS on the broker in production. Never commit broker passwords to git.' },
    ],
  },
  {
    slug: 'device-offline-troubleshooting',
    title: 'Troubleshooting offline devices',
    summary: 'Why a device shows offline and how to fix connectivity.',
    categoryId: 'devices-iot',
    tags: ['troubleshooting', 'mqtt', 'offline'],
    readMinutes: 6,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'A device is online when the platform receives a recent status or telemetry message on the correct topic with valid JSON.' },
      { type: 'h2', text: 'Checklist' },
      { type: 'ol', items: [
        'Confirm MQTT_ENABLED=true on the API and the broker is reachable from the gateway.',
        'Verify topic path matches the dashboard exactly (org, system, client ID).',
        'Check username/password and that the client ID is unique on the broker.',
        'Ensure clock sync on the gateway — use ISO 8601 timestamps in payloads.',
        'Look at API logs for parse errors or rejected payloads.',
      ]},
      { type: 'h2', text: 'Industrial inverters' },
      { type: 'p', text: 'Inverters often need a Modbus or vendor API adapter on a Raspberry Pi gateway. One registered mqttClientId should represent one logical device in SolarTech.' },
      { type: 'callout', variant: 'tip', text: 'Run publish-once from infra/gateway to isolate broker issues before debugging firmware.' },
    ],
  },
  {
    slug: 'dashboard-and-alerts',
    title: 'Dashboard and production alerts',
    summary: 'Read KPI cards, charts, and notification events.',
    categoryId: 'systems-monitoring',
    tags: ['dashboard', 'analytics', 'alerts'],
    readMinutes: 5,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'The dashboard summarizes total capacity, live power, energy today, and system health across your organization.' },
      { type: 'h2', text: 'Key metrics' },
      { type: 'ul', items: [
        'Power output (W) — instantaneous generation from telemetry',
        'Energy today (kWh) — cumulative daily energy per device or system',
        'System status — derived from device heartbeats and thresholds',
      ]},
      { type: 'h2', text: 'Notifications' },
      { type: 'p', text: 'Open Notifications in the sidebar for in-app events (device offline, quotation updates, maintenance assigned). Email and SMS depend on your organization notification settings.' },
      { type: 'callout', variant: 'info', text: 'Analytics and AI forecasting require sufficient historical telemetry — typically a few days of consistent publishing.' },
    ],
  },
  {
    slug: 'maintenance-work-orders',
    title: 'Maintenance and work orders',
    summary: 'Create tickets, assign technicians, and track SLAs.',
    categoryId: 'operations',
    tags: ['maintenance', 'crm', 'technician'],
    readMinutes: 5,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Maintenance helps solar companies track corrective and preventive work across their fleet.' },
      { type: 'h2', text: 'Typical workflow' },
      { type: 'ol', items: [
        'Create a ticket linked to a system (e.g. inverter fault, low production).',
        'Set priority and due date; attach notes or photos if available.',
        'Assign a technician; they update status from the field.',
        'Close the ticket when resolved and record root cause for reporting.',
      ]},
      { type: 'p', text: 'Roles: solar_company and installer users can create tickets; technician role is optimized for updates and dispatch lists.' },
    ],
  },
  {
    slug: 'installer-marketplace',
    title: 'Installer marketplace',
    summary: 'List your business, service areas, and get discovered by homeowners.',
    categoryId: 'operations',
    tags: ['marketplace', 'installers', 'leads'],
    readMinutes: 4,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Verified installers appear in the Marketplace with ratings, service areas, and portfolio projects.' },
      { type: 'h2', text: 'Improving your profile' },
      { type: 'ul', items: [
        'Complete business name, description, and service cities.',
        'Upload certifications and past project photos.',
        'Keep avgRating high by closing jobs and collecting reviews.',
        'Featured listings (when enabled by admin) appear at the top of search.',
      ]},
      { type: 'callout', variant: 'tip', text: 'Link marketplace leads to quotations in SolarTech so ROI and monitoring stay on one platform.' },
    ],
  },
  {
    slug: 'billing-and-invoices',
    title: 'Billing and invoices',
    summary: 'Create invoices, record payments, and view revenue stats.',
    categoryId: 'billing',
    tags: ['billing', 'invoices', 'stripe'],
    readMinutes: 6,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Billing lets your organization invoice clients for installs, O&M retainers, or monitoring subscriptions. Revenue stats aggregate paid and outstanding amounts.' },
      { type: 'h2', text: 'Invoice lifecycle' },
      { type: 'ol', items: [
        'Create an invoice with line items, tax, and due date.',
        'Send to client (status: sent).',
        'Client pays via Stripe or manual methods (GCash, bank transfer, cash).',
        'Mark paid or let Stripe webhooks update status automatically.',
      ]},
      { type: 'h2', text: 'Stripe setup' },
      { type: 'p', text: 'Configure STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in the API environment. Without Stripe, use manual payment recording from the invoice row actions.' },
      { type: 'callout', variant: 'warning', text: 'Platform subscription billing (Starter / Professional plans) is separate from client invoices — contact support for plan upgrades until self-serve checkout is enabled.' },
    ],
  },
  {
    slug: 'subscription-plans',
    title: 'Subscription plans and limits',
    summary: 'Starter, Professional, and Enterprise caps on users, systems, and devices.',
    categoryId: 'billing',
    tags: ['pricing', 'plans', 'limits'],
    readMinutes: 4,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Plans limit how many users, solar systems, and IoT devices your organization can manage. Exceeding limits may block new registrations until you upgrade.' },
      { type: 'h2', text: 'Plan tiers (marketing)' },
      { type: 'ul', items: [
        'Starter — small installers, up to a handful of systems',
        'Professional — AI analytics, Smart City access, API',
        'Enterprise — unlimited scale, white-label, custom integrations',
      ]},
      { type: 'p', text: 'See the Pricing section on the marketing site for current PHP pricing. Your organization admin can view usage under Settings → Organization.' },
    ],
  },
  {
    slug: 'roles-and-permissions',
    title: 'Roles and permissions',
    summary: 'What each role can access in the dashboard.',
    categoryId: 'account',
    tags: ['rbac', 'roles', 'security'],
    readMinutes: 5,
    updatedAt: '2026-05-28',
    body: [
      { type: 'h2', text: 'Role overview' },
      { type: 'ul', items: [
        'super_admin — full platform admin',
        'solar_company — systems, quotations, billing, maintenance',
        'installer — quotations, devices, marketplace profile',
        'technician — maintenance updates',
        'client — read-only production and invoices',
        'lgu_officer — Smart City analytics',
        'finance_officer — billing read/write',
      ]},
      { type: 'h2', text: 'Multi-factor authentication' },
      { type: 'p', text: 'Enable MFA under Settings → Security. After enrollment, login requires a TOTP code from your authenticator app.' },
      { type: 'callout', variant: 'tip', text: 'Use separate logins per team member instead of sharing one solar_company account — audit trails stay accurate.' },
    ],
  },
  {
    slug: 'ai-assistant',
    title: 'Using the AI Assistant (SolarBot)',
    summary: 'Ask questions about production, faults, and energy savings.',
    categoryId: 'systems-monitoring',
    tags: ['ai', 'solarbot', 'openai'],
    readMinutes: 4,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'SolarBot answers natural-language questions using your organization context when the OpenAI API key is configured on the server.' },
      { type: 'h2', text: 'Good questions to ask' },
      { type: 'ul', items: [
        'Why did System X produce less energy this week?',
        'Summarize open maintenance tickets.',
        'Explain payback on quotation #123.',
        'What should I check if voltage readings look unstable?',
      ]},
      { type: 'callout', variant: 'warning', text: 'AI responses are advisory. Always verify critical safety and electrical work with licensed engineers.' },
    ],
  },
  {
    slug: 'smart-city-for-lgu',
    title: 'Smart City analytics for LGUs',
    summary: 'Province maps, adoption stats, and carbon reporting.',
    categoryId: 'operations',
    tags: ['smart-city', 'lgu', 'gis'],
    readMinutes: 5,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Smart City aggregates anonymized or permitted system data across regions for LGU officers and enterprise accounts.' },
      { type: 'h2', text: 'Features' },
      { type: 'ul', items: [
        'Province-level installed capacity and system counts',
        'Heatmaps of solar adoption',
        'Estimated CO₂ reduction trends',
        'Overview cards for executive reporting',
      ]},
      { type: 'callout', variant: 'info', text: 'Access requires the lgu_officer role or Enterprise plan. Contact sales for city-wide data-sharing agreements.' },
    ],
  },
  {
    slug: 'diy-solar-guide',
    title: 'DIY solar installation overview',
    summary: 'Philippines-focused DIY path from site assessment to maintenance.',
    categoryId: 'getting-started',
    tags: ['diy', 'install', 'homeowner'],
    readMinutes: 6,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'p', text: 'The full interactive DIY guide with checklists lives on the marketing site at /diy. It covers seven phases aligned with local net metering and safety practice.' },
      { type: 'h2', text: 'Phases' },
      { type: 'ol', items: [
        'Assess consumption and roof',
        'Design system (use /calculators)',
        'Permits and DU net metering',
        'Procurement and safety gear',
        'Installation',
        'Commissioning and monitoring',
        'Maintenance',
      ]},
      { type: 'callout', variant: 'warning', text: 'Final grid interconnection must involve a licensed electrician and Distribution Utility approval.' },
    ],
  },
  {
    slug: 'solar-calculators',
    title: 'Using the free solar calculators',
    summary: 'System sizing, ROI, battery, and production tools at /calculators.',
    categoryId: 'quotations',
    tags: ['calculator', 'diy', 'sizing'],
    readMinutes: 4,
    updatedAt: '2026-05-28',
    body: [
      { type: 'p', text: 'Four calculators run in your browser using the same physics assumptions as the quotation engine: peak sun hours by province, 78% performance ratio, and Philippine equipment cost benchmarks.' },
      { type: 'ul', items: [
        'System Sizing — bill or kWh, roof area, grid type → kW, panels, cost, payback',
        'ROI & Payback — total cost vs annual savings with 25-year chart',
        'Battery Backup — daily load and outage hours → kWh and cost',
        'Energy Output — kW and location → daily/monthly/annual kWh',
      ]},
      { type: 'callout', variant: 'tip', text: 'After estimating, register and create a formal quotation to save results and share with clients.' },
    ],
  },
  {
    slug: 'faq',
    title: 'Frequently asked questions',
    summary: 'Common questions about trials, API, and support.',
    categoryId: 'getting-started',
    tags: ['faq', 'support'],
    readMinutes: 3,
    updatedAt: '2026-05-28',
    featured: true,
    body: [
      { type: 'h3', text: 'Do I need to run the API and web together?' },
      { type: 'p', text: 'Yes for full functionality. From the repo root, run npm run dev so the API (port 4000) and web (port 3000) both start. Auth and register fail if only the web app is running.' },
      { type: 'h3', text: 'Is there a free trial?' },
      { type: 'p', text: 'The marketing site offers a 14-day trial without a credit card. Trial limits match the Starter tier unless sales upgrades you.' },
      { type: 'h3', text: 'Where is API documentation?' },
      { type: 'p', text: 'Swagger UI is at http://127.0.0.1:4000/api/docs in development.' },
      { type: 'h3', text: 'How do I get support?' },
      { type: 'p', text: 'Use in-app Notifications for system events. For account issues, email your account manager or support@solartech.ph (configure your real support address in production).' },
    ],
  },
];
